allowBuilds:
  msgpackr-extract: set this to true or false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
minimumReleaseAgeExclude:
  - opencode-durmemo@0.1.0 || 0.1.1 || 0.1.2 || 0.1.3 || 0.1.4 || 0.1.5 || 0.1.6 || 0.1.7
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
